### ISSUE TITLE
Add SCAN data to meta-data files

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/river_flow_notebooks#13]
Soil moisture is an important variable for forecasting river flows and predicting agricultural yields. The US has a network of [SCAN sites](https://nwcc-apps.sc.egov.usda.gov/imap/#version=169&elements=&networks=SCAN&states=!&counties=!&hucs=&minElevation=&maxElevation=&elementSelectType=all&activeOnly=true&activeForecastPointsOnly=false&hucLabels=false&hucIdLabels=false&hucParameterLabels=false&stationLabels=&overlays=&hucOverlays=&basinOpacity=100&basinNoDataOpacity=100&basemapOpacity=100&maskOpacity=0&mode=stations&openSections=dataElement,parameter,date,basin,elements,location,networks&controlsOpen=true&popup=&popupMulti=&popupBasin=&base=esriNgwm&displayType=inventory&basinType=6&dataElement=PREC&depth=-8&parameter=PCTAVG&frequency=DAILY&duration=mtd&customDuration=&dayPart=E&year=2018&month=11&day=1&monthPart=E&forecastPubMonth=6&forecastPubDay=1&forecastExceedance=50&useMixedPast=true&seqColor=1&divColor=3&scaleType=D&scaleMin=&scaleMax=&referencePeriodType=POR&referenceBegin=1981&referenceEnd=2010&minimumYears=20&hucAssociations=true&lat=36.509&lon=-95.976&zoom=4.5) although the network is sparse ~= 200 sites across the US; The SCAN could still prove valuable for specific gages especially in Utah and other states where there is a high concentration. 

- [x] Add to the meta-data the closest three to the gage SCAN sites. This should go under heading listing the 
- [x] Add code and several unit tests 
- [x] Updated all meta-data to include the SCAN sites 
- [x] Commit ETL notebook to this repository under `scan_etl`

**Comment by isaacmg** [comment]
We may pause this issue as of right now there is no easy API to access the SCAN data it appears. There is a package in R but we will have to look into for more detail. For now I would say we should precede ahead with the other code and potentially add the SCAN data at a later point.

**Comment by isaacmg** [comment]
https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/daily/2057:AL:SCAN|id=%22%22|name/-7,-1/stationId,TMAX::value,TMIN::value,PRCP::value,RHUM::value:hourly%20MEAN,WSPDX::value:hourly%20MAX,WSPDV::value:hourly%20MEAN,SRADV::value:hourly%20MEAN,LRADT::value,PVPV::value:hourly%20MEAN,SVPV::value:hourly%20MEAN,SMS:-2:value:hourly%20MEAN,SMS:-4:value:hourly%20MEAN,SMS:-8:value:hourly%20MEAN,SMS:-20:value:hourly%20MEAN,SMS:-40:value:hourly%20MEAN,STO:-2:value:hourly%20MEAN,STO:-4:value:hourly%20MEAN,STO:-8:value:hourly%20MEAN,STO:-20:value:hourly%20MEAN,STO:-40:value:hourly%20MEAN

This is a potential URL to use to generate the repo

here

**Comment by isaacmg** [comment]
https://docs.google.com/spreadsheets/d/1z2WHmvs-w2a9x8ztXGoEdCRD9ZcAnbrvP1iG5nY3WLM/edit?usp=sharing

**Comment by isaacmg** [comment]
https://docs.google.com/spreadsheets/d/1z2WHmvs-w2a9x8ztXGoEdCRD9ZcAnbrvP1iG5nY3WLM/edit?usp=sharing

**Comment by isaacmg** [comment]
Working NB https://colab.research.google.com/drive/1sO4IWUi04VuNh51_5Pqdxr68uLL7Q7ve?usp=sharing
