### ISSUE TITLE
Add meta-data paths to Sentinel 2 tiles for all gages

### ISSUE THREAD

**Issue by isaacmg** [AIStream-Peelout/river_flow_notebooks#6]
We need to add to the meta-data the path to the GCS buckets of sentinel-2 data. This should be stored in the meta-data under a field `SENTINEL_GCS_PATH`

- [x]  Write/verify helper function query index using Pandas
- [x]  Commit function
- [x] Run ETL script to add data for files and upload updated file to GCS.
- [x] Save ETL notebook to this repository

**Comment by isaacmg** [comment]
Complete #8
